### ISSUE TITLE
name 've' is not defined

### ISSUE THREAD

**Issue by meghakadole** [steventen/Simulink-Model-Parsing-Tools#1]
Hello, thank you for the code. I am using Mdlparser with python3.4.4. When i run the code with example . code throws error saying name 've' is not defined. Please help

**Comment by dsvf** [comment]
My guess is that for Python 3 compatibility, you have to change line 64 from "except ValueError, ve:" to "except ValueError as ve:"

**Comment by steventen** [comment]
Should be resolved by https://github.com/steventen/Simulink-Model-Parsing-Tools/pull/4
