### ISSUE TITLE
Please add an explicit license to the project

### ISSUE THREAD

**Issue by papb** [steventen/Simulink-Model-Parsing-Tools#3]
Hello @steventen, can you please add a `LICENSE` file to this project? It is important to clarify what others can do with it. I recommend the MIT License if you're in doubt. See an example [here](https://github.com/papb/zip/blob/7e47ca7540613a0d7d0001ae6d2f65a51b8475b6/license).

Or, at least a brief statement somewhere (even here) saying whether or not people can use it under which circumstances. Thanks!

**Comment by steventen** [comment]
Hi @papb,

I have added the license. Thanks

**Comment by papb** [comment]
Thank you very much 😁
